/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 72563bb6f530b797d981ac0031411697)
interface __BaseEnv_Env {
	GA_SITE_PROPERTY_ID: string;
	GITHUB_TOKEN: string;
	PROJECTS_CE_TOKEN: string;
	GA_SERVICE_ACCOUNT_KEY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GA_SITE_PROPERTY_ID" | "GITHUB_TOKEN" | "PROJECTS_CE_TOKEN" | "GA_SERVICE_ACCOUNT_KEY">> {}
}
