import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../src/components/icons");
const OUT = join(ROOT, "generated.ts");
const check = process.argv.includes("--check");
const require = createRequire(import.meta.url);
const SOLAR = JSON.parse(readFileSync(require.resolve("@iconify-json/solar/icons.json"), "utf8"));

// "solar:<name>" is Solar (CC BY 4.0), "simple:<slug>" Simple Icons (CC0), "custom:<file>" custom/<file>.svg.
function source(ref) {
  const [set, name] = ref.split(":");
  if (set === "solar") {
    const icon = SOLAR.icons[name];
    if (!icon) throw new Error(`icons.json: Solar has no "${name}"`);
    return `<svg viewBox="0 0 ${icon.width ?? SOLAR.width ?? 24} ${icon.height ?? SOLAR.height ?? 24}">${icon.body}</svg>`;
  }
  if (set === "simple") {
    const svg = readFileSync(require.resolve(`simple-icons/icons/${name}.svg`), "utf8");
    return svg.replace(/<title>[\s\S]*?<\/title>/, "").replace(' role="img"', ' fill="currentColor"');
  }
  if (set === "custom") return readFileSync(join(ROOT, "custom", `${name}.svg`), "utf8");
  throw new Error(`icons.json: unknown source "${ref}"`);
}

function entry(ref) {
  const match = source(ref)
    .trim()
    .match(/^<svg([^>]*)>([\s\S]*)<\/svg>$/);
  if (!match) throw new Error(`icons.json: ${ref} is not a single <svg> element`);
  const viewBox = match[1].match(/viewBox="([^"]*)"/)?.[1] ?? "0 0 24 24";
  const fill = /fill="currentColor"/.test(match[1]) ? "currentColor" : "none";
  return { viewBox, fill, body: match[2].replace(/\s*\n\s*/g, "").trim() };
}

const manifest = JSON.parse(readFileSync(join(ROOT, "icons.json"), "utf8"));
const names = Object.keys(manifest).sort();
const text = [
  "// Generated by scripts/generate-icons.mjs from icons.json. Do not edit.",
  "export const ICONS = {",
  ...names.map((name) => `  ${JSON.stringify(name)}: ${JSON.stringify(entry(manifest[name]))},`),
  "} as const;",
  "",
].join("\n");

const current = (() => {
  try {
    return readFileSync(OUT, "utf8");
  } catch {
    return "";
  }
})();
if (check) {
  if (current !== text) {
    console.error("icons: generated.ts is stale, run `bun run icons`");
    process.exit(1);
  }
  console.log(`icons: ${names.length} up to date`);
} else {
  if (current !== text) writeFileSync(OUT, text);
  console.log(`icons: ${names.length} icons${current === text ? ", unchanged" : " written"}`);
}
