/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagesRouteImport } from './routes/_pages'
import { Route as PlainRouteImport } from './routes/_plain'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as OpengraphImageRouteImport } from './routes/opengraph-image'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TwitterImageRouteImport } from './routes/twitter-image'
import { Route as PagesAnalyticsRouteImport } from './routes/_pages/analytics'
import { Route as PagesAttributionRouteImport } from './routes/_pages/attribution'
import { Route as PagesBlogRouteImport } from './routes/_pages/blog'
import { Route as PagesBucketListRouteImport } from './routes/_pages/bucket-list'
import { Route as PagesJourneyRouteImport } from './routes/_pages/journey'
import { Route as PagesLinksRouteImport } from './routes/_pages/links'
import { Route as PagesStatsRouteImport } from './routes/_pages/stats'
import { Route as PagesTechStackRouteImport } from './routes/_pages/tech-stack'
import { Route as PlainContactRouteImport } from './routes/_plain/contact'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as OgPageRouteImport } from './routes/og/page'
import { Route as ProjectsOgRouteImport } from './routes/projects/og'
import { Route as PagesProjectsIndexRouteImport } from './routes/_pages/projects/index'
import { Route as PagesProjectsSlugRouteImport } from './routes/_pages/projects/$slug'
import { Route as PlainDocsIndexRouteImport } from './routes/_plain/docs/index'
import { Route as PlainDocsSplatRouteImport } from './routes/_plain/docs/$'
import { Route as PlainLegalPrivacyRouteImport } from './routes/_plain/legal/privacy'
import { Route as PlainLegalTermsRouteImport } from './routes/_plain/legal/terms'
import { Route as OgDocsSplatRouteImport } from './routes/og/docs/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/_pages',
  getParentRoute: () => rootRouteImport,
} as any)
const PlainRoute = PlainRouteImport.update({
  id: '/_plain',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const OpengraphImageRoute = OpengraphImageRouteImport.update({
  id: '/opengraph-image',
  path: '/opengraph-image',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TwitterImageRoute = TwitterImageRouteImport.update({
  id: '/twitter-image',
  path: '/twitter-image',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesAnalyticsRoute = PagesAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PagesRoute,
} as any)
const PagesAttributionRoute = PagesAttributionRouteImport.update({
  id: '/attribution',
  path: '/attribution',
  getParentRoute: () => PagesRoute,
} as any)
const PagesBlogRoute = PagesBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => PagesRoute,
} as any)
const PagesBucketListRoute = PagesBucketListRouteImport.update({
  id: '/bucket-list',
  path: '/bucket-list',
  getParentRoute: () => PagesRoute,
} as any)
const PagesJourneyRoute = PagesJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => PagesRoute,
} as any)
const PagesLinksRoute = PagesLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => PagesRoute,
} as any)
const PagesStatsRoute = PagesStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => PagesRoute,
} as any)
const PagesTechStackRoute = PagesTechStackRouteImport.update({
  id: '/tech-stack',
  path: '/tech-stack',
  getParentRoute: () => PagesRoute,
} as any)
const PlainContactRoute = PlainContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PlainRoute,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OgPageRoute = OgPageRouteImport.update({
  id: '/og/page',
  path: '/og/page',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsOgRoute = ProjectsOgRouteImport.update({
  id: '/projects/og',
  path: '/projects/og',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesProjectsIndexRoute = PagesProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => PagesRoute,
} as any)
const PagesProjectsSlugRoute = PagesProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => PagesRoute,
} as any)
const PlainDocsIndexRoute = PlainDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => PlainRoute,
} as any)
const PlainDocsSplatRoute = PlainDocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => PlainRoute,
} as any)
const PlainLegalPrivacyRoute = PlainLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => PlainRoute,
} as any)
const PlainLegalTermsRoute = PlainLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => PlainRoute,
} as any)
const OgDocsSplatRoute = OgDocsSplatRouteImport.update({
  id: '/og/docs/$',
  path: '/og/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/opengraph-image': typeof OpengraphImageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/twitter-image': typeof TwitterImageRoute
  '/analytics': typeof PagesAnalyticsRoute
  '/attribution': typeof PagesAttributionRoute
  '/blog': typeof PagesBlogRoute
  '/bucket-list': typeof PagesBucketListRoute
  '/journey': typeof PagesJourneyRoute
  '/links': typeof PagesLinksRoute
  '/stats': typeof PagesStatsRoute
  '/tech-stack': typeof PagesTechStackRoute
  '/contact': typeof PlainContactRoute
  '/api/og': typeof ApiOgRoute
  '/api/search': typeof ApiSearchRoute
  '/og/page': typeof OgPageRoute
  '/projects/og': typeof ProjectsOgRoute
  '/projects/$slug': typeof PagesProjectsSlugRoute
  '/docs/$': typeof PlainDocsSplatRoute
  '/legal/privacy': typeof PlainLegalPrivacyRoute
  '/legal/terms': typeof PlainLegalTermsRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/projects/': typeof PagesProjectsIndexRoute
  '/docs/': typeof PlainDocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/opengraph-image': typeof OpengraphImageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/twitter-image': typeof TwitterImageRoute
  '/analytics': typeof PagesAnalyticsRoute
  '/attribution': typeof PagesAttributionRoute
  '/blog': typeof PagesBlogRoute
  '/bucket-list': typeof PagesBucketListRoute
  '/journey': typeof PagesJourneyRoute
  '/links': typeof PagesLinksRoute
  '/stats': typeof PagesStatsRoute
  '/tech-stack': typeof PagesTechStackRoute
  '/contact': typeof PlainContactRoute
  '/api/og': typeof ApiOgRoute
  '/api/search': typeof ApiSearchRoute
  '/og/page': typeof OgPageRoute
  '/projects/og': typeof ProjectsOgRoute
  '/projects/$slug': typeof PagesProjectsSlugRoute
  '/docs/$': typeof PlainDocsSplatRoute
  '/legal/privacy': typeof PlainLegalPrivacyRoute
  '/legal/terms': typeof PlainLegalTermsRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/projects': typeof PagesProjectsIndexRoute
  '/docs': typeof PlainDocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pages': typeof PagesRouteWithChildren
  '/_plain': typeof PlainRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/opengraph-image': typeof OpengraphImageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/twitter-image': typeof TwitterImageRoute
  '/_pages/analytics': typeof PagesAnalyticsRoute
  '/_pages/attribution': typeof PagesAttributionRoute
  '/_pages/blog': typeof PagesBlogRoute
  '/_pages/bucket-list': typeof PagesBucketListRoute
  '/_pages/journey': typeof PagesJourneyRoute
  '/_pages/links': typeof PagesLinksRoute
  '/_pages/stats': typeof PagesStatsRoute
  '/_pages/tech-stack': typeof PagesTechStackRoute
  '/_plain/contact': typeof PlainContactRoute
  '/api/og': typeof ApiOgRoute
  '/api/search': typeof ApiSearchRoute
  '/og/page': typeof OgPageRoute
  '/projects/og': typeof ProjectsOgRoute
  '/_pages/projects/$slug': typeof PagesProjectsSlugRoute
  '/_plain/docs/$': typeof PlainDocsSplatRoute
  '/_plain/legal/privacy': typeof PlainLegalPrivacyRoute
  '/_plain/legal/terms': typeof PlainLegalTermsRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/_pages/projects/': typeof PagesProjectsIndexRoute
  '/_plain/docs/': typeof PlainDocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manifest.webmanifest'
    | '/opengraph-image'
    | '/sitemap.xml'
    | '/twitter-image'
    | '/analytics'
    | '/attribution'
    | '/blog'
    | '/bucket-list'
    | '/journey'
    | '/links'
    | '/stats'
    | '/tech-stack'
    | '/contact'
    | '/api/og'
    | '/api/search'
    | '/og/page'
    | '/projects/og'
    | '/projects/$slug'
    | '/docs/$'
    | '/legal/privacy'
    | '/legal/terms'
    | '/og/docs/$'
    | '/projects/'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manifest.webmanifest'
    | '/opengraph-image'
    | '/sitemap.xml'
    | '/twitter-image'
    | '/analytics'
    | '/attribution'
    | '/blog'
    | '/bucket-list'
    | '/journey'
    | '/links'
    | '/stats'
    | '/tech-stack'
    | '/contact'
    | '/api/og'
    | '/api/search'
    | '/og/page'
    | '/projects/og'
    | '/projects/$slug'
    | '/docs/$'
    | '/legal/privacy'
    | '/legal/terms'
    | '/og/docs/$'
    | '/projects'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/_pages'
    | '/_plain'
    | '/manifest.webmanifest'
    | '/opengraph-image'
    | '/sitemap.xml'
    | '/twitter-image'
    | '/_pages/analytics'
    | '/_pages/attribution'
    | '/_pages/blog'
    | '/_pages/bucket-list'
    | '/_pages/journey'
    | '/_pages/links'
    | '/_pages/stats'
    | '/_pages/tech-stack'
    | '/_plain/contact'
    | '/api/og'
    | '/api/search'
    | '/og/page'
    | '/projects/og'
    | '/_pages/projects/$slug'
    | '/_plain/docs/$'
    | '/_plain/legal/privacy'
    | '/_plain/legal/terms'
    | '/og/docs/$'
    | '/_pages/projects/'
    | '/_plain/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagesRoute: typeof PagesRouteWithChildren
  PlainRoute: typeof PlainRouteWithChildren
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  OpengraphImageRoute: typeof OpengraphImageRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TwitterImageRoute: typeof TwitterImageRoute
  ApiOgRoute: typeof ApiOgRoute
  ApiSearchRoute: typeof ApiSearchRoute
  OgPageRoute: typeof OgPageRoute
  ProjectsOgRoute: typeof ProjectsOgRoute
  OgDocsSplatRoute: typeof OgDocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages': {
      id: '/_pages'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_plain': {
      id: '/_plain'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opengraph-image': {
      id: '/opengraph-image'
      path: '/opengraph-image'
      fullPath: '/opengraph-image'
      preLoaderRoute: typeof OpengraphImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twitter-image': {
      id: '/twitter-image'
      path: '/twitter-image'
      fullPath: '/twitter-image'
      preLoaderRoute: typeof TwitterImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/analytics': {
      id: '/_pages/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof PagesAnalyticsRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/attribution': {
      id: '/_pages/attribution'
      path: '/attribution'
      fullPath: '/attribution'
      preLoaderRoute: typeof PagesAttributionRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/blog': {
      id: '/_pages/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof PagesBlogRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/bucket-list': {
      id: '/_pages/bucket-list'
      path: '/bucket-list'
      fullPath: '/bucket-list'
      preLoaderRoute: typeof PagesBucketListRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/journey': {
      id: '/_pages/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof PagesJourneyRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/links': {
      id: '/_pages/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof PagesLinksRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/stats': {
      id: '/_pages/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof PagesStatsRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/tech-stack': {
      id: '/_pages/tech-stack'
      path: '/tech-stack'
      fullPath: '/tech-stack'
      preLoaderRoute: typeof PagesTechStackRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_plain/contact': {
      id: '/_plain/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PlainContactRouteImport
      parentRoute: typeof PlainRoute
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/page': {
      id: '/og/page'
      path: '/og/page'
      fullPath: '/og/page'
      preLoaderRoute: typeof OgPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/og': {
      id: '/projects/og'
      path: '/projects/og'
      fullPath: '/projects/og'
      preLoaderRoute: typeof ProjectsOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/projects/': {
      id: '/_pages/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof PagesProjectsIndexRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/projects/$slug': {
      id: '/_pages/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof PagesProjectsSlugRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_plain/docs/': {
      id: '/_plain/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof PlainDocsIndexRouteImport
      parentRoute: typeof PlainRoute
    }
    '/_plain/docs/$': {
      id: '/_plain/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof PlainDocsSplatRouteImport
      parentRoute: typeof PlainRoute
    }
    '/_plain/legal/privacy': {
      id: '/_plain/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof PlainLegalPrivacyRouteImport
      parentRoute: typeof PlainRoute
    }
    '/_plain/legal/terms': {
      id: '/_plain/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof PlainLegalTermsRouteImport
      parentRoute: typeof PlainRoute
    }
    '/og/docs/$': {
      id: '/og/docs/$'
      path: '/og/docs/$'
      fullPath: '/og/docs/$'
      preLoaderRoute: typeof OgDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PagesRouteChildren {
  PagesAnalyticsRoute: typeof PagesAnalyticsRoute
  PagesAttributionRoute: typeof PagesAttributionRoute
  PagesBlogRoute: typeof PagesBlogRoute
  PagesBucketListRoute: typeof PagesBucketListRoute
  PagesJourneyRoute: typeof PagesJourneyRoute
  PagesLinksRoute: typeof PagesLinksRoute
  PagesStatsRoute: typeof PagesStatsRoute
  PagesTechStackRoute: typeof PagesTechStackRoute
  PagesProjectsSlugRoute: typeof PagesProjectsSlugRoute
  PagesProjectsIndexRoute: typeof PagesProjectsIndexRoute
}

const PagesRouteChildren: PagesRouteChildren = {
  PagesAnalyticsRoute: PagesAnalyticsRoute,
  PagesAttributionRoute: PagesAttributionRoute,
  PagesBlogRoute: PagesBlogRoute,
  PagesBucketListRoute: PagesBucketListRoute,
  PagesJourneyRoute: PagesJourneyRoute,
  PagesLinksRoute: PagesLinksRoute,
  PagesStatsRoute: PagesStatsRoute,
  PagesTechStackRoute: PagesTechStackRoute,
  PagesProjectsSlugRoute: PagesProjectsSlugRoute,
  PagesProjectsIndexRoute: PagesProjectsIndexRoute,
}

const PagesRouteWithChildren = PagesRoute._addFileChildren(PagesRouteChildren)

interface PlainRouteChildren {
  PlainContactRoute: typeof PlainContactRoute
  PlainDocsSplatRoute: typeof PlainDocsSplatRoute
  PlainLegalPrivacyRoute: typeof PlainLegalPrivacyRoute
  PlainLegalTermsRoute: typeof PlainLegalTermsRoute
  PlainDocsIndexRoute: typeof PlainDocsIndexRoute
}

const PlainRouteChildren: PlainRouteChildren = {
  PlainContactRoute: PlainContactRoute,
  PlainDocsSplatRoute: PlainDocsSplatRoute,
  PlainLegalPrivacyRoute: PlainLegalPrivacyRoute,
  PlainLegalTermsRoute: PlainLegalTermsRoute,
  PlainDocsIndexRoute: PlainDocsIndexRoute,
}

const PlainRouteWithChildren = PlainRoute._addFileChildren(PlainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagesRoute: PagesRouteWithChildren,
  PlainRoute: PlainRouteWithChildren,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  OpengraphImageRoute: OpengraphImageRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TwitterImageRoute: TwitterImageRoute,
  ApiOgRoute: ApiOgRoute,
  ApiSearchRoute: ApiSearchRoute,
  OgPageRoute: OgPageRoute,
  ProjectsOgRoute: ProjectsOgRoute,
  OgDocsSplatRoute: OgDocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
